version = 1

test_patterns = ["*/test/**"]

exclude_patterns = [
  "public/**,",
  "dist/**"
]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "mongo",
    "nodejs",
    "browser"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"
